### ISSUE TITLE
代码似乎不全啊

### ISSUE THREAD

**Issue by AsuradaYuci** [wuyang1903220154/Video-based-person-ReID-with-Attribute-information#1]

**Comment by wuyang1903220154** [comment]
你好这篇文章里有完整论文代码和介绍https://zhuanlan.zhihu.com/p/143552995，我是按照它的论文写得，但是现在已经很长时间没看了，有很多忘记了，希望能够帮助到你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wuyang1903220154/Video-based-person-ReID-with-Attribute-information"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 中午11:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wuyang1903220154/Video-based-person-ReID-with-Attribute-information] 代码似乎不全啊 (Issue #1)

**Comment by wuyang1903220154** [comment]
我看了一下代码，是差model和config这两个包，我给加里面了，因为对github用不是非常熟悉所以导致错误了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wuyang1903220154/Video-based-person-ReID-with-Attribute-information"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 中午11:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wuyang1903220154/Video-based-person-ReID-with-Attribute-information] 代码似乎不全啊 (Issue #1)

**Comment by AsuradaYuci** [comment]
@wuyang1903220154 好的 谢谢
